### ISSUE TITLE
2024 Q3 update by 黄敬国

### ISSUE THREAD

**Issue by bt7-vip** [housesigma/hr-interview#2]
一、写一个定时执行的Bash脚本，**每月的一号凌晨1点** 对 MongoDB 中 test.user_logs 表进行备份、清理

- 首先备份上个月的数据，备份完成后打包成.gz文件
- 备份文件通过sfpt传输到 **Backup [bak@bak.ipo.com]** 服务器上，账户已经配置在~/.ssh/config;
- 备份完成后，再对备份过的数据进行清理: **create_on [2024-01-01 03:33:11]** ;
- 如果脚本执行失败或者异常，则调用 [https://monitor.ipo.com/webhook/mongodb ];
- 这个表每日数据量大约在 **200w** 条, 单条数据未压缩的存储大小约 **200B**;

脚本文件`backup_db.sh`

```shell
#!/bin/bash

# MongoDB 相关配置
MONGO_HOST="localhost"
MONGO_PORT="27017"
MONGO_DB="test"
MONGO_COLLECTION="user_logs"
BACKUP_DIR="/path/to/backup"
BACKUP_FILE="$BACKUP_DIR/user_logs_$LAST_MONTH.gz"
LAST_MONTH=$(date -d "1 month ago" +%Y%m)
SFTP_HOST="bak.ipo.com"
WEBHOOK_URL="https://monitor.ipo.com/webhook/mongodb"

# 创建备份目录
mkdir -p $BACKUP_DIR
echo $(date "+%Y-%m-%d %X") 创建目录$BACKUP_DIR
# 备份上个月的数据
echo $(date "+%Y-%m-%d %X") 开始备份上月数据
mongoexport --host $MONGO_HOST --port $MONGO_PORT --db $MONGO_DB --collection $MONGO_COLLECTION --query "{create_on: {\$gte: new Date('$LAST_MONTH-01T00:00:00Z'), \$lt: new Date('$(date +\%Y-\%m-01)T00:00:00Z')}}" --out - | gzip > $BACKUP_FILE
# 检查备份是否成功
if [ $? -eq 0 ]; then
	echo $(date "+%Y-%m-%d %X") 备份成功
    echo $(date "+%Y-%m-%d %X") 开始传输文件
    sftp $SFTP_HOST <<EOF
put $BACKUP_FILE
EOF

    # 检查sftp传输是否成功
    if [ $? -eq 0 ]; then
    	echo $(date "+%Y-%m-%d %X") 传输成功
        echo $(date "+%Y-%m-%d %X") 开始清理数据库
        mongo $MONGO_DB --eval "db.$MONGO_COLLECTION.remove({create_on: {\$gte: new Date('$LAST_MONTH-01T00:00:00Z'), \$lt: new Date('$(date +\%Y-\%m-01)T00:00:00Z')}})"
        echo $(date "+%Y-%m-%d %X") 清理结束
    else
    	echo $(date "+%Y-%m-%d %X") 传输失败
        # sftp传输失败，调用webhook
        curl -X POST $WEBHOOK_URL -d "message=SFTP transfer failed for $BACKUP_FILE"
    fi
else
	echo $(date "+%Y-%m-%d %X") 备份失败
    # 备份失败，调用webhook
    curl -X POST $WEBHOOK_URL -d "message=Backup failed for $MONGO_COLLECTION"
fi
```

设置定时任务

```
# crontab -e
0 1 1 * * /path/to/backup_db.sh >> /var/log/mongodb_backup.log 2>&1
```

二、根据要求提供一份Nginx配置：

- 域名：ipo.com, 支持https、HTTP/2
- 非http请求经过301重定向到https
- 根据UA进行判断，如果包含关键字 **"Google Bot"**, 反向代理到 server_bot[bot.ipo.com] 去处理
- /api/{name} 路径的请求通过**unix sock**发送到本地 **php-fpm**，文件映射 **/www/api/{name}.php**
- /api/{name} 路径下需要增加限流设置，只允许每秒1.5个请求，超过限制的请求返回 **http code 429**
- /static/ 目录下是纯静态文件
- 其它请求指向目录 **/www/ipo/**, 查找顺序 index.html --> public/index.html --> /api/request

```config
# 主 Nginx 配置
server {
    # 监听 80 端口，用于重定向 http 到 https
    listen 80;
    server_name ipo.com www.ipo.com;
    
    # 所有 http 请求重定向到 https
    return 301 https://$host$request_uri;
}

server {
    # 监听 443 端口，启用 HTTPS 和 HTTP/2
    listen 443 ssl http2;
    server_name ipo.com www.ipo.com;

    # SSL 配置（根据实际情况修改路径和证书信息）
    ssl_certificate /etc/nginx/ssl/ipo.com.crt;
    ssl_certificate_key /etc/nginx/ssl/ipo.com.key;

    # 安全的 SSL 协议配置
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # 判断 User-Agent 并反向代理到 bot.ipo.com
    if ($http_user_agent ~* "Google Bot") {
        return 301 $scheme://bot.ipo.com$request_uri;
    }

    # 静态文件处理
    location /static/ {
        root /www/ipo;
        # 禁止访问目录列出
        autoindex off;
    }

    # /api/{name} 请求处理
    location ~ ^/api/(.+)$ {

        # 文件映射到 /www/api/{name}.php
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /www/api/$1.php;
		
        # 限流，每秒最多 1.5 个请求
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=1.5r/s;
        limit_req zone=api_limit burst=5 nodelay;
        error_page 429 = @rate_limit;
    }

    # 限流触发时返回 429 状态码
    location @rate_limit {
        return 429;
    }

    # 处理除静态文件和 API 外的其他请求
    location / {
        root /www/ipo;

        # 按顺序查找 index.html、public/index.html，然后代理到 /api/request
        try_files /index.html /public/index.html /api/request;
    }

    # 处理 /api/request
    location @api_request {
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /www/api/request.php;
    }
}

```

三、在生产环境中，应用程序是通过Haproxy来读取Slave集群，但是偶尔会产生 **SQLSTATE[HY000]: General error: 2006 MySQL server has gone away** 的错误，请根据经验，给出一排查方案与可能的方向，与开发一起定位问题, 现已经排查：

- 故障发生时，服务器之间防火墙正常，服务器之间可以正常通信;
- 故障SQL均可以正常查询，同时不存在性能问题;
- 故障频率没有发现特别规律，与服务器负载没有正相关;
- 查看各服务的日志，只发现了错误信息，但没有进一步的说明;

```mermaid
graph LR;
    Service-->Haproxy;
    Haproxy-->Slave_01;
    Haproxy-->Slave_02;
    Haproxy-->Slave_03;
    Haproxy-->Slave_04;
```

根据题目提供信息，定位问题数据库连接失败。

以下为排查思路

1：收集故障日志，分别收集12，24，36，48小时报错日志，取最小故障间隔与最大故障间隔。

2：排查超时限制导致故障

	- 在sql不存在性能瓶颈的情况下，增加数据库连接超时时间。
	-  将超时时间设置大于最小故障间隔时间，如果后续故障间隔时间增加，初步判断为数据库连接超时时间导致报错。
	-  在sql不存在瓶颈的情况下继续增加超时时间至最大故障间隔，如果故障消失，可判断为数据库连接超时时间导致报错。
	-  如果在增加超时时间后，故障增加，沟通开发连接前增加连接健康检测。

3：排查特定操作导致故障

	- 如果故障间隔明显少于已设置的超时时间。排除超时时间限制导致故障。
	-  咨询开发，故障发生时，执行的什么操作及发起请求的相关模块。触发故障的操作、请求发起模块是否趋向统一。
	-  针对特定操作，请求模块，检查是否有在连接时设置连接检查，检查相关sql语句是否会触发故障。

4：测试网络波动

	- 长测service到haproxy网络，排除网络波动导致故障。

5：配置服务日志，等待故障触发。

- 查询haproxy日志，确认请求到达haproxy。
- 查看请求被分配到那个slave，收集多次故障请求分配的节点，分析是否有规律。
- 如果存在规律，则将特定salve设置下线，查看故障是否恢复。

以上为排查偶发性连接故障的大致思路，排查方式根据实际业务环境，灵活调整。在排查中需要获取更多相关日志信息以及梳理整个请求，接收，处理，返回流程。排查可能存在的问题。

四、有一个简单的三层 Web 应用，包含前端（frontend）、中间层（backend），和数据库（database）三部分。这些应用都已经打包成 Docker 镜像，现在需要部署在 Kubernetes 中。 该集群是一个全新部署的集群，除了 kube-proxy, CoreDNS, CNI (Calico) 外没有部署任何应用。请根据下面的要求分别提供部署所需的所有 yaml 定义及部署说明，可以使用 helm 等工具。

具体要求如下：

>```
> 1. 前端服务（frontend）：
>  - 需要通过外部域名：frontend.example.com访问并支持 https，可以self-signed
>  - 支持自动扩缩容，根据 CPU (80%) 使用率在 2 到 10 个 Pod 之间调整实例数量
>  - 该 Pod 需要配置 health check, HTTP 协议 9090 端口
>```

- 创建一个configmap，为pod提供配置文件。将80端口重定向到443，提供https访问，提供9090检测端口

```
# cat frontend-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cert
data:
  frontend.example.com.conf: |
    server {
      listen 443 ssl;
      server_name frontend.example.com www.frontend.example.com;
      ssl_certificate /opt/ssl/frontend.example.com.crt;
      ssl_certificate_key /opt/ssl/frontend.example.com.key;
      ssl_session_timout 300;
      ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
      ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
      ssl_prefer_server_ciphers on;
      include /etc/nginx/conf.d/*.cfg;
      location / {
        root /usr/share/nginx/html;
      }

    }

    server {
      listen 80;
      server_name frontend.example.com www.frontend.example.com;
      return 301 https://$host$request_uri;
    server {
      listen 9090; #在9090端口提供健康检测
      location /health {
        return 200 'OK';
        add_header Content-Type text/plain;      
    }
    }
```

- 创建一个secret，向pod提供自签证书。

```
# kubectl create secret tls frontend-secret --cert=/opt/ssl/frontend.example.com.crt --key=/opt/ssl/frontend.example.com.key --dry-run=client -o yaml | tee frontend-scert.yml
```

- 创建deploymen，设置pod的cpu限制资源为1，请求资源为1。服务对外暴露端口80,443。配置健康检测。

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "1
          limits:
            cpu: "1"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443      
        - name: liveness-port
          containerPort: 9090
        livenessProbe: #配置健康检测
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 3
          periodSeconds: 3       
        
---
apiVersion: v1
kind: Service #对外暴露服务
metadata:
  name: frontend
  labels:
    app: nginx
spec:
  ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  selector:
    app: nginx
  type: LoadBalancer    
```

- 创建HorizontalPodAutoscaler，设置cpu使用率80%，自动容缩副本，最小2，最大10

```
# kubectl autoscale deployment nginx-deployment --cpu-percent=80 --min=2 --max=10
```

> ```
> 2. 中间层服务（backend）：
> - 仅供前端服务调用，不能对外部暴露
> - 支持通过环境变量来配置对 database 的访问，ENV KEY: DB_HOST/DB_NAME/DB_USER/DB_PASS...
> - 为了保证高可用性，至少要有 3个Pod 同时存活，同时需要 **尽可能** 避免多个 Pod 运行在同一个 Node 上
> ```

- 部署中间层服务，pod设置4副本，均衡分布到node中。设置环境变量。使用networkpolicy控制仅前端服务访问

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image
          env:
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: your_db_name
            - name: DB_USER
              value: your_db_user
            - name: DB_PASS
              value: your_db_password
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - backend
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service #通过service暴露端口
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy #配置networkpolicy,仅允许前端访问
metadata: 
  name: frontend-port-ingress
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
```

> ```
> 3. 数据库服务（database）：
> - 数据库只允许中间层服务访问，不能通过 ClusterIP 之外的方式暴露
> - 需要考虑持久化问题，数据存储在 /var/lib/mysql 目录下, 确保 Pod 崩溃或重建后数据不丢失
> ```

- 在指定node创建pv
- 为pod创建pvc
- 创建数据库并挂载pvc
- 创建service暴露服务
- 创建networkpolicy限制只能前端访问

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv #在指定标签的node节点创建pv
spec:
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: disktype # 指定node标签
              operator: In
              values:
                - ssd # 这里是标签 disktype 的值
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" #指定位置
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc #创建pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: backend
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-mysql
        tier: mysql
    spec:
      containers:
      - image: database
        name: database
        env:
        - name: DB_ROOT_PASSWORD
          value：root_password
        - name: DB_DATABASE
          value: backend
        - name: DB_USER
          value: backend
        - name: DB_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: database
        volumeMounts:
        - name: database-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: database-persistent-storage
        persistentVolumeClaim:
          claimName: database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: backend-database
spec:
  ports:
    - port: 3306
  selector:
    app: database
    tier: mysql
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy #配置networkpolicy,仅允许前端访问
metadata: 
  name: database-ingress
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
```
